CREATE TABLE "GCG_3850_PO_COGS"(
 "TERMINAL" CHAR(3),
 "GL_ACCOUNT" CHAR(15),
 "PO_NUMBER" CHAR(7),
 "VENDOR_NAME" CHAR(30),
 "DATE_RECEIVED" DATE,
 "PART" CHAR(20),
 "LOCATION" CHAR(2),
 "PART_DESCRIPTION" CHAR(30),
 "QUANTITY_RECEIVED" DOUBLE,
 "COST" DOUBLE,
 "PO_Line" CHAR(4),
 "PO_GL" CHAR(15));
